{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pgpulse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgpulse.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: app.kubernetes.io/component
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "pgpulse.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      {{- with .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      honorLabels: true
{{- end }}
